export const ERROR_CODES = {
  // Users
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  INVALID_USER_DATA: 'INVALID_USER_DATA',

  // Permissions
  DELETE_NOT_ALLOWED: 'DELETE_NOT_ALLOWED',
  UNAUTHORIZED_ACTION: 'UNAUTHORIZED_ACTION',

  // Validation
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INVALID_EMAIL: 'INVALID_EMAIL',
  EMAIL_ALREADY_TAKEN: 'EMAIL_ALREADY_TAKEN',

  // Pagination & Search
  INVALID_PAGE_NUMBER: 'INVALID_PAGE_NUMBER',
  INVALID_PER_PAGE: 'INVALID_PER_PAGE',

  // Server
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
