export const ERROR_CODES = {
  // Shop Items
  ITEM_NOT_FOUND: 'ITEM_NOT_FOUND',
  ITEM_UNAVAILABLE: 'ITEM_UNAVAILABLE',

  // Payment
  PAYMENT_PROCESSING_FAILED: 'PAYMENT_PROCESSING_FAILED',
  INVALID_PAYMENT_REQUEST: 'INVALID_PAYMENT_REQUEST',
  INVALID_CARD_NUMBER: 'INVALID_CARD_NUMBER',
  EMPTY_CART: 'EMPTY_CART',

  // Validation
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INVALID_ITEM_ID: 'INVALID_ITEM_ID',
  DUPLICATE_ITEMS: 'DUPLICATE_ITEMS',

  // Rate Limiting
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // Server
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
